---

- name: installing httpd(apache) server
  yum: httpd state=latest

- name: stat directories if they exist
  stat:
    path: "{{ item }}"
  with_items:
    - /var/www/html/internal
    - /var/www/html/external
    - /var/www/html/cached
  register: myvar

- debug var=myvar.results

- name: create directory if they don't exist
  file:
    path: "{{ item.invocation.module_args.path }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  with_items: "{{ stat.results }}"

- name: Copy multiple files into document root
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{item.mode}}"
  with_items:
     - { src: 'internal.html',dest: '/var/www/html/internal/index.html', mode: '0644'}
     - { src: 'external.html',dest: '/var/www/html/external/index.html', mode: '0644'}
     - { src: 'cached.html',dest: '/var/www/html/cached/index.html', mode: '0644'}
