---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: nginx_yum_repo_enabled | bool

- name: Ensure nginx is installed.
  package:
    name: "{{ nginx_package_name }}"
    state: present

- name: Copy nginx.conf file 
  copy:
    src: nginx.conf
    dest: '{{ nginx_conf_file_path }}'


- name: copy virtual host config file
  template:
        src: default.conf.j2
        dest: '{{ nginx_default_vhost_path }}'

- name: install modsecurity module
  yum: pkg={{ nginx_modsecurity_rpm }} state=present
